"""initial migration

Revision ID: f987fa5cfd49
Revises: 
Create Date: 2024-10-30 22:39:36.022186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f987fa5cfd49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular_destinations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_destinations',
    sa.Column('guid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('guid')
    )
    # ### end Alembic commands ###
